### PR TITLE
headers relative path javascript

### PR DESCRIPTION
**Pull request by kvakanet**
Patch for javascript relative path without this in Debian javascripts not downloaded if url http(s)://server/fusiondirectory/

### CODE REVIEW

**Comment by bilbo-the-hobbit** [comment]
hello,

for which version of the debian packages is this patch ?

Cheers

**Comment by kvakanet** [comment]
Hello!

I tested on debian 7.9 (wheezy).
I think on the next versions debian of the patch can be used.
The problem is that the script is taken from the root path(/javascript) instead of a relative path(javascript).

**Comment by bilbo-the-hobbit** [comment]
hello,

checked and you are right, this will be in the .1.0.9.3 that will be uploaded to debian very soon, and will be our official 1.0.10 due soon

**Comment by bilbo-the-hobbit** [comment]
Hello,

closing this as this is fixed in 1.0.10 and in 1.0.9.3 sson to be upload into debian

**Pull request closed without merging**
